name: deploy to remote

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      SSH_USER: ${{ secrets.SSH_USER }}
      DEPLOY_PATH: ${{ vars.DEPLOY_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add SSH host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H -p $SSH_PORT $SSH_HOST >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: |
          rsync -avz --delete \
            --exclude=".git/" \
            --exclude=".github/" \
            --exclude=".DS_Store" \
            --exclude="README.md" \
            --exclude=".htaccess" \
            --exclude=".htpasswd" \
            -e "ssh -p $SSH_PORT" \
            ./ $SSH_USER@$SSH_HOST:$DEPLOY_PATH
